#!/usr/bin/env bash

focused_monitor=$(hyprctl monitors -j | jq -r '.[] | select(.focused) | .x')
mode=$1
arg=$2

if [ "$arg" == "left" ]; then
    monitor_position_operator="<"
    next_focused_monitor=$(hyprctl monitors -j | jq -r ".[] | select(.x $monitor_position_operator $focused_monitor) | .id " | tail -n 1)
else
    monitor_position_operator=">"
    next_focused_monitor=$(hyprctl monitors -j | jq -r ".[] | select(.x $monitor_position_operator $focused_monitor) | .id " | head -n 1)
fi

function handle(){
    case $1 in
        monitoradded*)
            $HOME/.scripts/hypr/wallpaper apply $arg ;;
    esac
}

case "$mode" in
    "handle")
        socat - "UNIX-CONNECT:/tmp/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock" | while read -r line; do handle "$line"; done; ;;
    "focus")
        hyprctl dispatch focusmonitor $next_focused_monitor
        ;;
    "move")
        hyprctl dispatch movecurrentworkspacetomonitor $next_focused_monitor
        ;;
esac

