#!/usr/bin/env bash

monitors_count=$(hyprctl monitors -j | jq length)
default_monitor=$(hyprctl monitors 0 -j | jq ".[]|.name")

function lid_on(){
    hyprctl reload
    hyprctl dispatch dpms on
}

function lid_off(){
    if (( "$monitors_count" > 1 )); then
        hyprctl keyword monitor "eDP-1, disable"
    else
        loginctl lock-session
        hyprctl dispatch dpms off
    fi
}

case "$1" in
    "on") lid_on ;;
    "off") lid_off ;;
esac


