- hosts: localhost
  gather_facts: true
  vars_files:
      - ./variables.yml
  pre_tasks:
      - import_tasks: ./setup_directory.yml
      - import_tasks: ./setup_personal.yml
      - import_tasks: ./setup_build.yml
  tasks:
      - import_tasks: ./tasks/_common/config.yml
      - import_tasks: ./tasks/_common/tools.yml
      - import_tasks: ./tasks/_common/packages.yml
      - import_tasks: ./tasks/_common/node.yml
      - import_tasks: ./tasks/_common/php.yml
      - import_tasks: ./tasks/_common/go.yml
      - import_tasks: ./tasks/_common/rust.yml
      - import_tasks: ./tasks/_common/neovim.yml
      - import_tasks: ./tasks/_common/zsh.yml
      - import_tasks: ./tasks/_common/git.yml
      - import_tasks: ./tasks/_common/apps.yml
      - import_tasks: ./tasks/_common/nerdfont.yml

      - import_tasks: ./tasks/mac/flameshot.yml
      - import_tasks: ./tasks/mac/browser.yml

      - import_tasks: ./htasks/mac/setting.yml
      - import_tasks: ./tasks/mac/setting.yml
