- hosts: localhost
  gather_facts: true
  vars_files:
      - ./variables.yml
  pre_tasks:
      - import_tasks: ./setup_directory.yml
      - import_tasks: ./setup_personal.yml
      - import_tasks: ./setup_build.yml
  tasks:
      - import_tasks: ./tasks/_hyprwm/audio.yml
      - import_tasks: ./tasks/_hyprwm/bluetooth.yml

      - import_tasks: ./tasks/_common/config.yml
      - import_tasks: ./tasks/_common/tools.yml
      - import_tasks: ./tasks/_common/packages.yml
      - import_tasks: ./tasks/_common/node.yml
      - import_tasks: ./tasks/_common/php.yml
      - import_tasks: ./tasks/_common/go.yml
      - import_tasks: ./tasks/_common/rust.yml
      - import_tasks: ./tasks/_common/neovim.yml
      - import_tasks: ./tasks/_common/zsh.yml
      - import_tasks: ./tasks/_common/git.yml
      - import_tasks: ./tasks/_common/apps.yml
      - import_tasks: ./tasks/_common/nerdfont.yml

      - import_tasks: ./tasks/_hyprwm/config.yml
      - import_tasks: ./tasks/_hyprwm/packages.yml
      - import_tasks: ./tasks/_hyprwm/hyprland.git.yml
      - import_tasks: ./tasks/_hyprwm/ags.yml
      - import_tasks: ./tasks/_hyprwm/anyrun.yml
      - import_tasks: ./tasks/_hyprwm/clipboard.yml
      - import_tasks: ./tasks/_hyprwm/tlp.yml
      - import_tasks: ./tasks/_hyprwm/fcitx.yml
      - import_tasks: ./tasks/_hyprwm/udiskie.yml
      - import_tasks: ./tasks/_hyprwm/font.yml
      - import_tasks: ./tasks/_hyprwm/theme.yml
      - import_tasks: ./tasks/_hyprwm/sddm.yml
      - import_tasks: ./tasks/_hyprwm/grub.yml

      - import_tasks: ./tasks/arch/flameshot.yml
      - import_tasks: ./tasks/arch/browser.yml

      - import_tasks: ./tasks/_hyprwm/setting.yml
      - import_tasks: ./tasks/_common/setting.yml
      - import_tasks: ./tasks/arch/setting.yml
