- name: Installing ags dependencies for arch
  become: true
  community.general.pacman:
      update_cache: true
      state: 'present'
      name:
          - vala
          - gjs
          - dart-sass
          - gtk3
          - json-glib
          - gobject-introspection
          - gtk-layer-shell
          - libdbusmenu-gtk3
          - libappindicator-gtk3
          - upower
          - wireplumber
  when: ansible_facts.distribution == ARCH
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# --------------------- Building proccess --------------------- #

- name: Downloading ags & astal package
  ansible.builtin.git:
      repo: 'https://github.com/aylur/{{ item.repo }}.git'
      dest: '{{ HOME }}/{{ item.repo }}'
      depth: 1
      recursive: true
      refspec: '{{ item.refspec | default(omit) }}'
      version: '{{ item.version | default(omit) }}'
  loop:
      - repo: astal
        version: '5b2a0e8905fc32ac603437c22fb6eaee6adeafd8'
        refspec: '5b2a0e8905fc32ac603437c22fb6eaee6adeafd8'
      - repo: ags
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# ----- Astal io ----- #
- name: Building astal io library
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/astal/io
      meson setup --reconfigure --prefix /usr build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Installing astal io library
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/astal/io
      meson install -C build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# ----- Astal gtk ----- #
- name: Building astal gtk library
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/astal/gtk3
      meson setup --reconfigure --prefix /usr build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Installing astal gtk library
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/astal/gtk3
      meson install -C build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# ----- Astal battery ----- #
- name: Building astal battery library
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/battery
      meson setup --reconfigure --prefix /usr build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Installing astal battery package
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/battery
      meson install -C build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# ----- Astal bluetooth ----- #
- name: Building astal bluetooth library
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/bluetooth
      meson setup --reconfigure --prefix /usr build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Installing astal bluetooth package
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/bluetooth
      meson install -C build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# ----- Astal network ----- #
- name: Building astal network library
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/network
      meson setup --reconfigure --prefix /usr build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Installing astal network package
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/network
      meson install -C build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# ----- Astal wireplumber ----- #
- name: Building astal wireplumber library
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/wireplumber
      meson setup --reconfigure --prefix /usr build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Installing astal wireplumber package
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/wireplumber
      meson install -C build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# ----- Astal hyprland ----- #
- name: Building astal hyprland library
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/hyprland
      meson setup --reconfigure --prefix /usr build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Installing astal hyprland package
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/hyprland
      meson install -C build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# ----- Astal notifd ----- #
- name: Building astal notifd library
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/notifd
      meson setup --reconfigure --prefix /usr build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Installing astal notifd package
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/notifd
      meson install -C build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# ----- Astal mpris ----- #
- name: Building astal mpris library
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/mpris
      meson setup --reconfigure --prefix /usr build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Installing astal mpris package
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/mpris
      meson install -C build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# ----- Astal tray ----- #
- name: Building astal tray library
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/tray
      meson setup --reconfigure --prefix /usr build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Installing astal tray package
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lib/tray
      meson install -C build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# ----- Astal gjs ----- #
- name: Building astal gjs lang
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lang/gjs
      meson setup --reconfigure --prefix /usr build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Installing astal gjs lang
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/astal/lang/gjs
      meson install -C build
  tags:
      - ags
      - ags_standanlone
      - hyprwm

# ----- Ags ----- #
- name: Downloading ags package
  ansible.builtin.shell: |
      cd {{ HOME }}/ags
      go install -ldflags "\
          -X 'main.gtk4LayerShell=$(pkg-config --variable=libdir gtk4-layer-shell-0)/libgtk4-layer-shell.so' \
          -X 'main.astalGjs=$(pkg-config --variable=srcdir astal-gjs)'"
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Installing ags package
  become: true
  ansible.builtin.copy:
      src: '{{ GOPATH.stdout }}/bin/ags'
      dest: '/usr/local/bin'
      mode: 0755
  tags:
      - ags
      - ags_standanlone
      - hyprwm

- name: Generating ags types
  ansible.builtin.shell: |
      export PREFIX={{ HOME }}/.node/n
      export N_PREFIX={{ HOME }}/.node
      export N_CACHE_PREFIX={{ HOME }}/.node
      export PATH={{ HOME }}/.node/n/bin:$PATH
      export PATH={{ HOME }}/.node/bin:$PATH

      ags types
  tags:
      - ags
      - ags_standanlone
      - hyprwm
