- name: Installing rust toolchain
  become: true
  ansible.builtin.shell: |
      export RUSTUP_HOME={{ XDG_CACHE_HOME }}/rustup
      export CARGO_HOME={{ CARGO_HOME }}

      if [[ ! -d {{ CARGO_HOME }} ]]; then
          curl --proto '=https' \
               --tlsv1.2 \
               -sSf \
               https://sh.rustup.rs \
          | sh -s -- --quiet -y --no-modify-path
      fi
  tags:
      - rust

- name: Adding rust to the path
  ansible.builtin.blockinfile:
      path: '{{ item }}'
      create: true
      prepend_newline: true
      marker: '#--------- {mark} ---------#'
      marker_begin: StartRust
      marker_end: EndRust
      block: |
          export CARGO_HOME="{{ CARGO_HOME }}"
          export RUSTUP_HOME="{{ XDG_CACHE_HOME }}/rustup"
          export PATH="$PATH:{{ CARGO_HOME }}/bin"
  loop:
      - '{{ XDG_CONFIG_HOME }}/zsh/path.zsh'
      - '{{ HOME }}/.bashrc'
  tags:
      - rust
