source = ./envars.conf
source = ./startup.conf
source = ./monitor.conf
source = ./colors.conf
source = ./keybind.conf

source = ./rules/workspaces.conf
source = ./rules/layers.conf
source = ./rules/windows.conf
source = ./rules/windows.conf

general {
    layout = master
    gaps_in = 4 
    gaps_out = 8
    border_size = 1

    col.active_border =  $charcoal $base $base $base $charcoal 90deg 
    col.inactive_border = $charcoal $base $base $base $charcoal 180deg

    allow_tearing = true
    extend_border_grab_area = 40
    resize_on_border = true
}

master {
    new_on_top = true
    mfact = 0.5
}

dwindle {
    force_split = 2
    pseudotile = true
    smart_split = false
    preserve_split = true
}

binds {
    focus_preferred_method = 0
    movefocus_cycles_fullscreen = true
    workspace_back_and_forth = false
    disable_keybind_grabbing = true
    workspace_center_on = 0
}

input {
    kb_layout = us
    kb_variant =,
    kb_options = grp:shifts_toggle, caps:swapescape  
    follow_mouse = 1 
    sensitivity = 0
    mouse_refocus = true
    special_fallthrough = true
    natural_scroll = true

    touchpad {
        clickfinger_behavior = true
        tap-and-drag = true
        drag_lock = true
        middle_button_emulation = true
        natural_scroll = true
    }
}

cursor {
    hide_on_key_press = false
    hide_on_touch = true
    warp_on_change_workspace = true
    persistent_warps = true
    warp_on_change_workspace = true
}

gestures {
    workspace_swipe = true
    workspace_swipe_invert = true
    workspace_swipe_touch = true
    workspace_swipe_touch_invert = false
    workspace_swipe_distance = 400
    workspace_swipe_cancel_ratio = 0.3
    workspace_swipe_fingers = 4
    workspace_swipe_create_new = false
    workspace_swipe_cancel_ratio = 0.2
    workspace_swipe_min_speed_to_force = 5
}

decoration {
    rounding = 8 

    dim_inactive = false
    dim_strength = 0.1
    active_opacity = 1
    inactive_opacity = 0.94
    fullscreen_opacity = 1

    shadow {
        enabled = true
        ignore_window = true
        offset = 0 0;
        range = 14
        render_power = 4
        color = rgba(000000A6)
    }

    blur {
        enabled = true
        size = 16
        passes = 2
        new_optimizations = true
        ignore_opacity = true
        xray = false
        popups = true
        popups_ignorealpha = 0.6
    }
}

animations {
    enabled = true
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = menu_decel, 0.1, 1, 0, 1

    animation = layers, 0
    animation = fade, 0
    animation = windows, 0
    animation = windows, 0
    animation = windowsIn, 0
    animation = workspaces, 1, 0.3, menu_decel, slide
    animation = specialWorkspace, 1, 0.3, md3_decel, slidevert
}

xwayland {
    enabled = true
    force_zero_scaling = false
}

misc {
    vfr = true
    focus_on_activate = true
    background_color = $lavender
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true  
    initial_workspace_tracking = 0
    new_window_takes_over_fullscreen = 2
    disable_hyprland_logo = true
    background_color = $base
}
