- name: Scanning basepath {{ name }} config dir
  ansible.builtin.find:
      paths: '{{ playbook_dir }}/{{ config_path }}'
      file_type: directory
      excludes: '*tasks'
      hidden: true
  register: base_dir
  tags: '{{ tags }}'

- name: Scanning {{ name }} config dir
  ansible.builtin.find:
      paths: '{{ item.path }}'
      file_type: any
      hidden: true
  register: config_dir
  loop: '{{ base_dir.files }}'
  loop_control:
      label: '{{ item.path }}'
  tags: '{{ tags }}'

- name: Linking {{ name }} config dir
  ansible.builtin.file:
      src: >-
          {{
            item[1].path if (item[1] is mapping and 'path' in item[1]) 
            else item
          }}
      dest: >-
          {{ HOME }}/{{
            item[1].path.split('/')[-2:] | join('/') if (item[1] is mapping and 'path' in item[1]) 
            else item | basename
          }}
      state: link
      force: true
      unsafe_writes: true
  loop: >-
      {{
        q('subelements', config_dir.results, 'files', {'skip_missing': True})
        +
        lookup('fileglob', '{{ playbook_dir }}/{{ config_path }}/*', wantlist=True)
        +
        lookup('fileglob', '{{ playbook_dir }}/{{ config_path }}/.*', wantlist=True)
      }}
  loop_control:
      label: >-
          {{
            item[1].path if (item[1] is mapping and 'path' in item[1]) 
            else item
          }}
  tags: '{{ tags }}'
