#!/usr/bin/env bash

focused_monitor=$(hyprctl monitors -j | jq -r '.[] | select(.focused) | .x')
mode=$1
direction=$2

if [ "$direction" == "left" ]; then
    local monitor_position_operator="<";
    local next_focused_monitor=$(hyprctl monitors -j | jq -r ".[] | select(.x $monitor_position_operator $focused_monitor) | .id " | tail -n 1)
else
    local monitor_position_operator=">";
    local next_focused_monitor=$(hyprctl monitors -j | jq -r ".[] | select(.x $monitor_position_operator $focused_monitor) | .id " | head -n 1)
fi

function handle(){
    case $1 in
        monitoradded*)
            $HOME/.bin/hypr_wallpaper cycle ;;
    esac
}

case "$mode" in
    "handle")
        socat - "UNIX-CONNECT:/tmp/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock" | while read -r line; do handle "$line"; done; ;;
    "focus")
        hyprctl dispatch focusmonitor $next_focused_monitor
        ;;
    "move")
        hyprctl dispatch movecurrentworkspacetomonitor $next_focused_monitor
        ;;
esac

