#!/usr/bin/env bash

MODE=$1
WPP_PATH=$2
WPP_DEFAULT_DIR=$HOME/.wallpaper
check_hyprpaper=$(pgrep -x hyprpaper)

if [[ -z "$check_hyprpaper" ]]; then
    hyprpaper &
fi

function apply(){
    local monitors=($(hyprctl monitors -j | jq -r ".[].name"))

    if (( $(find "$WPP_DEFAULT_DIR/" -type d -name $WPP_PATH | wc -l) > 0 )); then
        WPP_PATH="$WPP_DEFAULT_DIR/$WPP_PATH"
    fi

    if [[ $WPP_PATH == '' ]]; then
        case $(date +%H) in
            05 | 06 | 07 | 08 | 09 | 10)
                WPP_PATH="$WPP_DEFAULT_DIR/monochrome"
                ;;
            11 | 12 | 13 | 14 | 15 | 16)
                WPP_PATH="$WPP_DEFAULT_DIR/pastel"
                ;;
            17 | 18 | 19 | 20 | 21 | 22)
                WPP_PATH="$WPP_DEFAULT_DIR/green"
                ;;
            23 | 00 | 01 | 02 | 03 | 04)
                WPP_PATH="$WPP_DEFAULT_DIR/dark"
                ;;
        esac
    fi

    for t in ${monitors[@]}; do
        if [[ -d $WPP_PATH ]]; then
            IMG="$(fd -t f . --full-path $WPP_PATH | shuf -n1)"
        else
            IMG=$WPP_PATH
            pkill -fic "bash $HOME/.bin/hypr_wallpaper daemon"
        fi

        hyprctl hyprpaper preload $IMG
        hyprctl hyprpaper wallpaper "$t,$IMG"

        sleep 0.1
        hyprctl hyprpaper unload $IMG
    done
}

function daemon(){
    local check_daemon=$(pgrep -fic "bash $HOME/.scripts/hypr_wallpaper daemon")

    if (( "$check_daemon" <= "1" )); then
        while true; do
            apply
            sleep 599
        done
    fi
}

case $MODE in
    "apply") apply ;;
    "daemon") daemon ;;
esac
