#!/usr/bin/env bash

MODE=$1
WPP_PATH=$2
WPP_DEFAULT_DIR=$HOME/.wallpaper
check_hyprpaper=$(pgrep -x hyprpaper)

if [[ -z "$check_hyprpaper" ]]; then
    hyprpaper &
fi

function get_wpp(){
    local WALLPAPER=$WPP_PATH
    local IMG=$WALLPAPER

    if [[ $WPP_PATH == '' ]]; then
        case $(date +%H) in
            05 | 06 | 07 | 08 | 09 | 10)
                WPP_PATH="monochrome"
                ;;
            11 | 12 | 13 | 14 | 15 | 16)
                WPP_PATH="pastel"
                ;;
            17 | 18 | 19 | 20 | 21 | 22)
                WPP_PATH="green"
                ;;
            23 | 00 | 01 | 02 | 03 | 04)
                WPP_PATH="dark"
                ;;
        esac
    fi

    if (( $(find "$WPP_DEFAULT_DIR/" -type d -name $WPP_PATH | wc -l) > 0 )); then
        WALLPAPER="$WPP_DEFAULT_DIR/$WPP_PATH"
    fi

    if [[ -d $WALLPAPER ]]; then
        IMG="$(fd -t f . --full-path $WALLPAPER | shuf -n1)"
    else
        IMG=$WALLPAPER
        pkill -fic "bash $HOME/.bin/hypr_wallpaper daemon"
    fi

    echo $IMG
}

function apply(){
    local monitors=($(hyprctl monitors -j | jq -r ".[].name"))

    IMG=$(get_wpp)

    for t in ${monitors[@]}; do
        hyprctl hyprpaper preload $IMG
        hyprctl hyprpaper wallpaper "$t,$IMG"

        sleep 0.1
        hyprctl hyprpaper unload $IMG
    done
}

function daemon(){
    local check_daemon=$(pgrep -fic "bash $HOME/.scripts/hypr_wallpaper daemon")

    if (( "$check_daemon" <= "1" )); then
        while true; do
            apply
            sleep 599
        done
    fi
}

case $MODE in
    "apply") apply ;;
    "daemon") daemon ;;
    "get_wpp") get_wpp ;;
esac
