- name: Checking wl-clipboard build directory
  ansible.builtin.stat:
      path: '{{ DOTFILES_CACHE }}/clipboard/build'
  register: clipboard_build
  tags:
      - clipboard
      - hyprwm

- name: Downloading wl-clipboard
  ansible.builtin.git:
      repo: https://github.com/bugaevc/wl-clipboard.git
      dest: '{{ DOTFILES_CACHE }}/wlclipboard'
      depth: 1
      recursive: true
      update: false
      version: '{{ WL_CLIPBOARD_VERSION }}'
  tags:
      - clipboard
      - hyprwm

- name: Compiling wl-clipboard
  ansible.builtin.shell: |
      cd {{ DOTFILES_CACHE }}/wlclipboard 
      meson setup build
      cd build
      ninja
  when: not clipboard_build.stat.exists
  tags:
      - clipboard
      - hyprwm

- name: Installing wl-clipboard
  become: true
  ansible.builtin.shell: |
      cd {{ DOTFILES_CACHE }}/wlclipboard
      meson install -C build
  tags:
      - clipboard
      - hyprwm

- name: Downloading cliphist
  ansible.builtin.shell: |
      export GOPATH={{ GOPATH }}

      {{ GOROOT }}/bin/go install go.senan.xyz/cliphist@latest
  tags:
      - clipboard
      - hyprwm

- name: Installing cliphist
  become: true
  ansible.builtin.copy:
      src: '{{ GOPATH }}/bin/cliphist'
      dest: /usr/local/bin
      mode: 0755
  tags:
      - clipboard
      - hyprwm
