- name: Installing hyprland package
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name:
          - qt5-wayland
          - qt6-wayland
          - socat
          - playerctl
          - brightnessctl
          - polkit-gnome
          - gnome-keyring

          - thunar
          - ristretto
          - mousepad
          - okular
          - file-roller
          - nm-connection-editor
          - pavucontrol

          - thunar-archive-plugin
          - xdg-user-dirs
          - gvfs
          - gvfs-mtp
          - ffmpegthumbnailer
          - tumbler
          - webp-pixbuf-loader
          - network-manager-applet
          - mpv-mpris
          - xorg-xhost
  tags:
      - hyprwm
