- name: Installing sddm
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name: ['sddm', 'qt6-svg', 'qt6-declarative']
  tags:
      - sddm
      - hyprwm

- name: Checking sddm theme
  ansible.builtin.stat:
      path: '{{ DOTFILES_CACHE }}/sddm-theme'
  register: sddm_theme
  tags:
      - sddm
      - hyprwm

- name: Downloading sddm theme
  ansible.builtin.uri:
      url: 'https://github.com/catppuccin/sddm/releases/download/{{ SDDM_THEME_VERSION }}/catppuccin-mocha.zip'
      dest: '{{ DOTFILES_CACHE }}/sddm-theme'
  when: not sddm_theme.stat.exists
  tags:
      - sddm
      - hyprwm

- name: Installing sddm theme
  become: true
  ansible.builtin.unarchive:
      src: '{{ DOTFILES_CACHE }}/sddm-theme'
      dest: /usr/share/sddm/themes
  tags:
      - sddm
      - hyprwm

- name: Configuring sddm autologin
  become: true
  ansible.builtin.ini_file:
      path: /etc/sddm.conf
      create: yes
      section: '{{ item.section }}'
      option: '{{ item.option }}'
      value: '{{ item.value }}'
      backup: true
  loop:
      - option: User
        value: '{{ USER }}'
        section: Autologin

      - option: Session
        value: hyprland-uwsm
        section: Autologin

      - option: Current
        value: catppuccin-mocha
        section: Theme
  tags:
      - sddm
      - hyprwm

- name: Enabling sddm with systemd
  become: true
  ansible.builtin.systemd:
      enabled: true
      name: sddm
  tags:
      - sddm
      - hyprwm
