- name: Download forbidden installsripts
  ansible.builtin.file:
      src: '{{ playbook_dir}}/archscripts'
      dest: '{{ HOME }}/.archscripts'
      state: 'link'
  tags:
      - personal

- name: Handle logind config
  ansible.builtin.ini_file:
      path: '/etc/sddm.conf'
      create: 'yes'
      section: 'Autologin'
      option: '{{ item.option }}'
      value: '{{ item.value }}'
      backup: true
      no_extra_spaces: true
  loop:
      - {option: 'HandlePowerKey', value: 'ignore'}
      - {option: 'HandleLidSwitch', value: 'ignore'}
  tags:
      - sddm
      - hyprwm
