- name: Copying ssh keys
  ansible.builtin.copy:
      src: '{{ playbook_dir }}/.ssh/'
      dest: '{{ HOME }}/.ssh'
      mode: 0600
  tags:
      - ssh
      - personal

- name: Authorizing public ssh key
  ansible.posix.authorized_key:
      user: '{{ USER }}'
      key: "{{ lookup('file', item) }}"
      state: 'present'
  loop: "{{ lookup('fileglob', '{{ HOME }}/.ssh/*.pub', wantlist=True) }}"
  tags:
      - ssh
      - personal

- name: Downloading personal repository
  ansible.builtin.git:
      repo: git@github.com:immoralJellyfish/{{ item.repo }}.git
      dest: '{{ item.dest }}'
      depth: 1
      update: false
      recursive: true
      accept_hostkey: true
  loop:
      - repo: personal
        dest: '{{ playbook_dir }}/.contents/personal'

      - repo: Notes
        dest: '{{ HOME }}/Documents/notes'
  tags:
      - personal
