#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(fd . "$HOME" "/run/media" "/media" "/volumes"\
            -t d -t l -u -i -d 8 \
            --exclude "**/snap/**" \
            --exclude "**/.git/**" \
            --exclude "**/tmp/**" \
            --exclude "**/node_modules/**" \
            --exclude "**RECYCLE_BIN**" \
            --exclude "**Windows**" \
            --exclude "**Local*Disk**" \
        --exclude "**Trash**" 2>/dev/null | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(echo $selected | tr -d ' ' | tr . _ | tr -d /)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c "$selected" -n main
    exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
    tmux new-session -ds $selected_name -c "$selected" -n main
fi

if [ -z $TMUX ]; then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi
